### PR TITLE
 Add packages for other linux

### PR DESCRIPTION
**Pull request by Kcchouette**
I just add my package I've installed to compile it on Archlinux.

Thanks

### CODE REVIEW

**Comment by maksis** [comment]
This doesn't list many of the required packages, such as OpenSSL, zlib and bzip2.

I'd prefer maintaining the compilation guide only for Ubuntu, but native installation packages could be created for different distributions (and then listed in the README).

https://github.com/airdcpp-web/airdcpp-webclient/issues/38
https://wiki.archlinux.org/index.php/creating_packages

**Comment by maksis** [comment]
There used to be an Arch package for airdcnano, which is probably closest to this client: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=airdcnano

**Comment by Kcchouette** [comment]
you're right :-)

**Comment by synaomen** [comment]
Now i work on .deb rls with Openbuildservice from Suse/Novell. But this is the first time that i do this and have deb build conflicts. i must read more package build howtos.....
U an look the current status here (nothing comlete atm):
[https://build.opensuse.org/package/show/home:synapsenstau/Airdcpp-Webclient](url)

**Comment by maksis** [comment]
:thumbsup:

**Comment by maksis** [comment]
I see that the Debian build fails because of the git version check and Web UI installation. I'll fix the build script to work without those.

**Comment by synaomen** [comment]
The Problem is, that npm will load the airdcpp-webui over internet, but OBS provide no network.
[https://en.opensuse.org/openSUSE:Packaging_nodejs](url)

**Comment by maksis** [comment]
Changes in the development branch should fix the problems. I'll close this pull request as it's not related to the Debian package (better use the issue tracker instead).

**Pull request closed without merging**
